<?php
$hydratorName = '';
if ($this->details) {
    $hydratorName = $this->details->hydratorName;
}
?>
namespace <?= $module ?>\V<?= $version ?>\Rest\<?= $resource ?>;
<?php if ($hydratorName == 'ArraySerializable') : // Entity class implementing ArraySerializableInterface ?>

    use Zend\Stdlib\ArraySerializableInterface;
    use ApigilityTools\Rest\Entity\EventAwareEntity;

    class <?= $classname ?>
    extends EventAwareEntity
    implements ArraySerializableInterface
    {

    }
<?php else : // Simple entity class ?>

    class <?= $classname ?>

    {
    }
<?php endif ?>
